### ISSUE TITLE
Plugin error, se repite el mismo mensaje

### ISSUE THREAD

**Issue by evermine** [evermine/DeadBack#2]
cuando ejecutas el comando /deadback
te salta el aviso "[DeadBack] You can only run this command after you die.". Aunque hayas muerto anteriormente

**Comment by iksaku** [comment]
Que raro :/ esto no debe pasar xD

**Comment by iksaku** [comment]
Oh espera! Ya encontre el error xD Dejame lo arreglo rapido...

**Comment by evermine** [comment]
vale

**Comment by evermine** [comment]
ok,voy a provar

**Comment by evermine** [comment]
Va bien

**Comment by evermine** [comment]
El error esta solucionado
