### ISSUE TITLE
Me puedes seguir en twitter para poder enviarte mensaje privado?

### ISSUE THREAD

**Issue by evermine** [evermine/DeadBack#3]
Porque no puedo enviarte mensajes privados si tu no me sigues, i así no hay que poner todo en publico

**Comment by iksaku** [comment]
Oye, esto no es para conversar xD si quieres mandame un mensaje privado en los foros de pocketmine ;)

**Comment by evermine** [comment]
como se envia un mensaje privado en pocketmine?

**Comment by evermine** [comment]
Se nota que soy nuevo xD
